# Generated by Django 4.0.2 on 2022-04-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_recipeingredient_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredient_recipe', to='main.Ingredient', verbose_name='Ingredients'),
        ),
    ]
